### ISSUE TITLE
ppa/deb repo

### ISSUE THREAD

**Issue by professorjamesmoriarty** [dangodai/soundcloud-m3u#3]
I've added this to my personal [ppa](https://launchpad.net/~twodopeshaggy/+archive/ubuntu/ppapackages) and [debian repo](http://shaggytwodope.github.io/repo.html). I'll be updating as with the aur package whenever any stable releases are tagged. Should you like to include them as sources in the readme that'd be great. Otherwise feel free to close this issue.

**Comment by dangodai** [comment]
Sure. Could you reply with the markdown you want added to the readme? I'm not familiar with Debian/Ubuntu packaging, so I'm not sure what people expect in the readme. Thanks.

**Comment by professorjamesmoriarty** [comment]
So steps for a ppa is pretty simple.

```sh
sudo add-apt-repository ppa:twodopeshaggy/ppapackages
sudo apt-get update
sudo apt-get install soundcloud-m3u
```

As for the debian repo, it can get pretty wordy in explaining the steps. You can grab the steps from [here](https://github.com/odeke-em/drive/blob/master/platform_packages.md) for debian and replace drive with soundcloud-m3u. For example:
```sh
sudo apt-add-repository 'deb http://shaggytwodope.github.io/repo ./'
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7086E9CC7EC3233B
sudo apt-key update
sudo apt-get update
sudo apt-get install soundcloud-m3u
```

**Comment by dangodai** [comment]
Added.
